SELECT * FROM tab;
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES WHERE LAST_NAME = 'Smith';

DESC EMPLOYEES;

SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES WHERE LAST_NAME = 'Smith';
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES WHERE LAST_NAME = 'Smith';

SELECT EMPLOYEE_ID as "ID", SALARY as "SAL" FROM EMPLOYEES;
SELECT EMPLOYEE_ID "ID", SALARY "SAL" FROM EMPLOYEES;

SELECT EMPLOYEE_ID "Á¾¾÷¿ø ID", SALARY "¿¬ºÀ" FROM EMPLOYEES WHERE LAST_NAME = 'Smith';

SELECT DISTINCT JOB_ID FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY >= 5000;

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE >= '04/01/01';

/* and */
SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50 and JOB_ID = 'SH_CLERK';

/* or */
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, MANAGER_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50 or MANAGER_ID = 124;

/* not */
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE NOT(DEPARTMENT_ID = 50);
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID <> 50;

/* SALARY 4000 ~ 8000 */
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY >= 4000 and SALARY <=8000;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN 4000 and 8000;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY = 6500 or SALARY = 7700 or SALARY = 13000;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY in (6500, 7700, 13000);

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE FIRST_NAME like 'D%';

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE FIRST_NAME like '%d';

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE FIRST_NAME like '_a%';

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE FIRST_NAME like '__a%';

/* not commission */
SELECT FIRST_NAME, LAST_NAME, COMMISSION_PCT FROM EMPLOYEES
WHERE COMMISSION_PCT is null;

/* commission */
SELECT FIRST_NAME, LAST_NAME, COMMISSION_PCT FROM EMPLOYEES
WHERE COMMISSION_PCT is not null;

/* ascending sort */
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
ORDER BY EMPLOYEE_ID;

/* descending sort */
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
ORDER BY EMPLOYEE_ID DESC;

