SELECT * FROM EMPLOYEES;

/* sysdate */
SELECT SYSDATE FROM DUAL;

/* months_between(date1, date2) */
SELECT FIRST_NAME, LAST_NAME, MONTHS_BETWEEN(SYSDATE, HIRE_DATE)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;

/* add_months() */
SELECT ADD_MONTHS(SYSDATE, 7) FROM DUAL;

/* next_day() */
SELECT NEXT_DAY(SYSDATE, '일요일') FROM DUAL;

/* last_day() */
SELECT LAST_DAY(SYSDATE) FROM DUAL;

/* to_char() */
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD') FROM DUAL;

/* to_date() */
SELECT TO_DATE('2015/03/04', 'YYYY/MM/DD') FROM DUAL;

/* nvl(): null값을 다른 데이터로 변경하는 함수 */
SELECT FIRST_NAME, LAST_NAME, NVL(COMMISSION_PCT, 0) COMMISSION FROM EMPLOYEES;

/* decode(): switch문의 역할을 하는 함수 */
SELECT DEPARTMENT_ID, DECODE(DEPARTMENT_ID, 20, '마케팅부', 60, '전산', 90, '경영부', '부서')
FROM EMPLOYEES;

/* case(): else if문과 같은 역할 함수 */
SELECT FIRST_NAME, DEPARTMENT_ID,
    CASE WHEN DEPARTMENT_ID = 20 THEN '마케팅부'
         WHEN DEPARTMENT_ID = 60 THEN '전산실'
         WHEN DEPARTMENT_ID = 90 THEN '경영부'
         ELSE ''
         END "부서명"
FROM EMPLOYEES;