/* group by 절 */
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

/* 부서별 급여 합계 */
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

/* 사용할 수 없음 (distinct는 그룹함수 사용 불가) */
SELECT DISTINCT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES;

/* 부서별 사원수와 평균 급여를 구해보자 */
SELECT DEPARTMENT_ID, SUM(SALARY), COUNT(SALARY), AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

/* 부서별 직급별 사원수와 평균 급여를 구해보자 */
SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY), COUNT(SALARY), AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY), COUNT(SALARY), AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID, JOB_ID;

SELECT DEPARTMENT_ID, JOB_ID,
TO_CHAR(SUM(SALARY), '999,999') 총급여,
TO_CHAR(AVG(SALARY), '999,999') 평균급여
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID, JOB_ID;

SELECT DEPARTMENT_ID, JOB_ID,
TO_CHAR(SUM(SALARY), '999,999') 총급여,
TO_CHAR(AVG(SALARY), '999,999') 평균급여
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID, JOB_ID;

/* having 절: 현재 부서별 사원수 */
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
WHERE DEPARTMENT_ID is not null
   /* AND COUNT(*) >= 10 where절에서는 그룹함수 사용불가 */
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) >= 10;

/* rollup: 그룹별 합계 정보를 추가해서 보여주는 함수 */
SELECT l.CITY, d.DEPARTMENT_NAME, e.JOB_ID,
COUNT(*) 사원수, SUM(e.SALARY) 총급여
FROM EMPLOYEES e, DEPARTMENTS d, LOCATIONS l
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
AND d.LOCATION_ID = l.LOCATION_ID
GROUP BY rollup(l.CITY, d.DEPARTMENT_NAME, e.JOB_ID)
ORDER BY l.CITY, d.DEPARTMENT_NAME, e.JOB_ID;