SELECT * FROM EMPLOYEES;

/* sum() */
SELECT SUM(SALARY) FROM EMPLOYEES;

/* count() */
SELECT COUNT(*) FROM EMPLOYEES;
SELECT COUNT(ALL EMPLOYEE_ID), COUNT(DISTINCT EMPLOYEE_ID) FROM EMPLOYEES;
SELECT COUNT(ALL FIRST_NAME), COUNT(DISTINCT FIRST_NAME) FROM EMPLOYEES;

/* avg() */
SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

/* max() */
SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT MAX(HIRE_DATE) FROM EMPLOYEES;

/* group function is not allowed where clause */
SELECT EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES WHERE SALARY = MAX(SALARY);
-- WHERE 조건절에서는 그룹함수()를 사용 할 수 없다!

/* min() */
SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT MIN(HIRE_DATE) FROM EMPLOYEES;

/* number function */
/* abs() */
SELECT ABS(-23) FROM DUAL;

/* sign() */
SELECT SIGN(23), SIGN(-23), SIGN(0) FROM DUAL;

/* round(n1, n2) */
SELECT ROUND(0.123), ROUND(0.543) FROM DUAL;
SELECT ROUND(0.12345678, 6), ROUND(2.3423455, 4) FROM DUAL;

/* trunc(n1, n2) */
SELECT TRUNC(1234.1234567) ZERO FROM DUAL;
SELECT TRUNC(1234.1234567, 0) ZERO FROM DUAL;

SELECT TRUNC(1234.1234567, 2) FROM DUAL;
SELECT TRUNC(1234.1234567, -1) FROM DUAL;

/* ceil() */
SELECT CEIL(32.8) CEIL FROM DUAL;
SELECT CEIL(32.3) CEIL FROM DUAL;

/* floor() */
SELECT FLOOR(32.8) FLOOR FROM DUAL;
SELECT FLOOR(32.3) FLOOR FROM DUAL;

/* power() */
SELECT POWER(4, 2) POWER FROM DUAL;

/* mod() */
SELECT MOD(7, 4) MOD FROM DUAL;

/* sqrt() */
SELECT SQRT(2), SQRT(3) FROM DUAL;