-- 없어진 기록 찾기
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID;

-- 있었는데요 없었습니다
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
WHERE A.DATETIME > (SELECT B.DATETIME
FROM ANIMAL_OUTS B
WHERE B.ANIMAL_ID = A.ANIMAL_ID)
ORDER BY DATETIME;

-- 오랜 기간 보호한 동물(1)
SELECT NAME, DATETIME
FROM (SELECT A.NAME, A.DATETIME
      FROM ANIMAL_INS A LEFT OUTER JOIN ANIMAL_OUTS B
      ON A.ANIMAL_ID = B.ANIMAL_ID
      WHERE B.ANIMAL_ID IS NULL
      ORDER BY DATETIME)
WHERE ROWNUM <= 3;